defaults:
  - _self_
  - ../env@env_cfg: calvin

skills_list: ["open_drawer", "close_drawer", "move_slider_left", "move_slider_right", "turn_on_lightbulb", "turn_off_lightbulb", "turn_on_led", "turn_off_led"]
input_dir: ${oc.env:DIWA_DATA_DIR}/expert/calvin-state-raw-50/
output_dir: ${oc.env:DIWA_DATA_DIR}/expert/calvin-state-raw-50/