defaults:
  - setup
  - ../lumos/config/datamodule@datamodule: static_gripper_cam
  - ../lumos/config/world_model@world_model: dreamer_v2
  - override ../lumos/config/datamodule/batch_sampler@datamodule.batch_sampler: ac_equidistant
  - _self_

exp_dir: ${wm_chk_dir}
wm_chk_dir: ${oc.env:DIWA_LOG_DIR}/wm/ckpts/vision64-ac5.ckpt
output_file: "visionwm64_ac5_features.pkl"
device: 0

datamodule:
  root_data_dir: ${root}/dataset/task_D_D_64
  action_chunk_data_dir: ${root}/dataset/task_D_D_ac5
  action_chunk_size: 5
  use_cached_data: true
