defaults:
  - setup
  - ../lumos/config/datamodule@datamodule: static_gripper_cam
  - ../lumos/config/world_model@world_model: dreamer_v2
  - _self_

  - override ../lumos/config/datamodule/proprioception_dims@datamodule.proprioception_dims: robot_full

exp_dir: ${wm_chk_dir}
wm_chk_dir: /path/to/your/model/checkpoint/X.ckpt
output_file: "visionwm_features.pkl"
device: 0
datamodule:
  root_data_dir: ${root}/dataset/libero/libero_90_calvin_fmt_64