defaults:
  - setup
  - logger: wandb
  - ../lumos/config/tensor_cores@_global_
  - ../lumos/config/callbacks@callbacks: wm_default
  - ../lumos/config/datamodule@datamodule: state
  - ../lumos/config/world_model@world_model: dreamer_v2_state
  - ../lumos/config/trainer@trainer: wm_default
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

log_dir: ${oc.env:DIWA_LOG_DIR}/wm/
script: wm

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.root_data_dir 